package ru.denis.forts3d.command;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.*;
import net.minecraft.commands.*;
import net.minecraft.network.chat.Component;
import net.neoforged.neoforge.event.RegisterCommandsEvent;
import ru.denis.forts3d.config.FortsConfig;
import ru.denis.forts3d.game.*;
import ru.denis.forts3d.registry.ModItems;

public final class FortsCommands {
 public static void register(RegisterCommandsEvent e){CommandDispatcher<CommandSourceStack>d=e.getDispatcher();d.register(Commands.literal("forts")
  .then(Commands.literal("status").executes(c->status(c.getSource())))
  .then(Commands.literal("join").then(Commands.argument("team",StringArgumentType.word()).suggests((c,b)->{b.suggest("red");b.suggest("blue");b.suggest("spectator");return b.buildFuture();}).executes(c->{var p=c.getSource().getPlayerOrException();var t=FortsTeam.byId(StringArgumentType.getString(c,"team"));return FortsMatchManager.get(c.getSource().getServer()).join(p,t)?1:0;})))
  .then(Commands.literal("giveadmin").requires(s->s.hasPermission(2)).executes(c->{c.getSource().getPlayerOrException().getInventory().add(ModItems.ADMIN_TABLET.toStack());return 1;}))
  .then(Commands.literal("match").requires(s->s.hasPermission(2)).then(Commands.literal("create").executes(c->{FortsMatchManager.get(c.getSource().getServer()).create();return 1;})).then(Commands.literal("start").executes(c->{FortsMatchManager.get(c.getSource().getServer()).start(c.getSource().getServer());return 1;})).then(Commands.literal("pause").executes(c->{FortsMatchManager.get(c.getSource().getServer()).pause();return 1;})).then(Commands.literal("stop").executes(c->{FortsMatchManager.get(c.getSource().getServer()).stop(c.getSource().getServer());return 1;})))
  .then(Commands.literal("resource").requires(s->s.hasPermission(2)).then(Commands.argument("team",StringArgumentType.word()).then(Commands.argument("type",StringArgumentType.word()).then(Commands.argument("amount",LongArgumentType.longArg(-1000000,1000000)).executes(c->{var b=FortsMatchManager.get(c.getSource().getServer()).bank(FortsTeam.byId(StringArgumentType.getString(c,"team")));if(b==null)return 0;long v=LongArgumentType.getLong(c,"amount");switch(StringArgumentType.getString(c,"type")){case"metal"->b.addMetal(v);case"energy"->b.addEnergy(v);case"ammo"->b.addAmmo(v);default->{return 0;}}return 1;})))))
  .then(Commands.literal("tech").requires(s->s.hasPermission(2)).then(Commands.argument("team",StringArgumentType.word()).then(Commands.argument("technology",StringArgumentType.word()).executes(c->{var b=FortsMatchManager.get(c.getSource().getServer()).bank(FortsTeam.byId(StringArgumentType.getString(c,"team")));if(b==null)return 0;try{return b.unlock(Technology.valueOf(StringArgumentType.getString(c,"technology").toUpperCase()))?1:0;}catch(Exception x){return 0;}}))))
  .then(Commands.literal("config").requires(s->s.hasPermission(2)).then(Commands.literal("list").executes(c->{c.getSource().sendSuccess(()->Component.literal("collapse="+FortsConfig.STRUCTURAL_COLLAPSE.get()+", worldDamage="+FortsConfig.WORLD_DAMAGE.get()+", friendlyFire="+FortsConfig.FRIENDLY_FIRE.get()+", maxProjectiles="+FortsConfig.MAX_PROJECTILES.get()+", buildRadius="+FortsConfig.BUILD_RADIUS.get()),false);return 1;})).then(Commands.literal("collapse").then(Commands.argument("value",BoolArgumentType.bool()).executes(c->{FortsConfig.STRUCTURAL_COLLAPSE.set(BoolArgumentType.getBool(c,"value"));return 1;}))).then(Commands.literal("worldDamage").then(Commands.argument("value",BoolArgumentType.bool()).executes(c->{FortsConfig.WORLD_DAMAGE.set(BoolArgumentType.getBool(c,"value"));return 1;}))).then(Commands.literal("friendlyFire").then(Commands.argument("value",BoolArgumentType.bool()).executes(c->{FortsConfig.FRIENDLY_FIRE.set(BoolArgumentType.getBool(c,"value"));return 1;}))).then(Commands.literal("maxProjectiles").then(Commands.argument("value",IntegerArgumentType.integer(16,8192)).executes(c->{FortsConfig.MAX_PROJECTILES.set(IntegerArgumentType.getInteger(c,"value"));return 1;}))).then(Commands.literal("buildRadius").then(Commands.argument("value",IntegerArgumentType.integer(16,1024)).executes(c->{FortsConfig.BUILD_RADIUS.set(IntegerArgumentType.getInteger(c,"value"));return 1;}))))));}
 private static int status(CommandSourceStack s){var m=FortsMatchManager.get(s.getServer());s.sendSuccess(()->Component.literal("Forts 3D: "+m.state()+", "+m.remainingTicks()/20+"s"),false);for(var t:new FortsTeam[]{FortsTeam.RED,FortsTeam.BLUE}){var b=m.bank(t);if(b!=null)s.sendSuccess(()->Component.literal(t.color()+t.id()+" M="+b.metal()+" E="+b.energy()+" A="+b.ammo()+" R="+m.reactorHealth(t)),false);}return 1;} private FortsCommands(){}
}
